apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dst-disk
spec:
  source:
      blank: {}
  storage:
    accessModes:
      - ReadWriteMany
    volumeMode: Block
    resources:
      requests:
        storage: 5Gi
