apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-live-storage-migration
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchExpressions:
          - key: cluster.kubernetes.io/cluster-name
            operator: In
            values:
              - lab
  template:
    metadata:
      name: '{{.name}}-demo-live-storage-migration'
    spec:
      project: default
      source:
        path: 'applicationsets/demo-live-storage-migration/manifests'
        repoURL: https://github.com/erkerc/gitops-demo/gitops-demo.git
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
      destination:
        server: '{{.server}}'
        namespace: demo-live-storage-migration

